/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosimplex;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author JFONSECACO
 */
public class Forma4Datos extends javax.swing.JFrame {

    /**
     * Creates new form Forma4Datos
     */
    int minMax;
    int var;
    int rest;
    
    public Forma4Datos(int minMax, int var, int rest) {
        JOptionPane.showMessageDialog(this,"Variables: "+var+" Restricciones: "+rest);
        initComponents();
        this.minMax = minMax;
        this.var = var;
        this.rest = rest;
        nuevosComponentes();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void nuevosComponentes(){
        jTextField = new JTextField[rest][var];
        
        for(int i=0;i<rest;i++){
           for(int j=0;j<var;j++){
                jTextField[i][j] = new javax.swing.JTextField();
                jTextField[i][j].setText(i+" "+j);
                //add(jTextField[i][j]);

            }

        }
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        
        //horizontal
        SequentialGroup sg1 = layout.createSequentialGroup();
        ParallelGroup[] pg1 = new ParallelGroup[var];
        
        sg1.addGap(50, 50, 50);
        
        for(int i = 0; i<var;i++){
            pg1[i]=layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false);
            for(int j = 0; j < rest; j++){
                pg1[i].addComponent(jTextField[j][i], javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE);
            }
            sg1.addGroup(pg1[i]);
            sg1.addGap(15, 15, 15);
        }
        
        sg1.addContainerGap(250,Short.MAX_VALUE);
        
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sg1)
        );

        
        //vertical
        SequentialGroup sg2 = layout.createSequentialGroup();
        ParallelGroup[] pg2 = new ParallelGroup[rest];
        
        sg2.addGap(73, 73, 73);
        
        for(int i=0;i<rest;i++){
            pg2[i]=layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE);
            for(int j=0;j<var;j++){
                pg2[i].addComponent(jTextField[i][j], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            }
            sg2.addGroup(pg2[i]);

            sg2.addGap(15,15,15);
        }
        
        sg2.addContainerGap(200, Short.MAX_VALUE);
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sg2)
        );

        pack();
        
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(203, 203, 203)
//                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(229, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(138, 138, 138)
//                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(189, Short.MAX_VALUE))
//        );
//
//        pack();
        
        
    }

    private javax.swing.JTextField[][] jTextField;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
